apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drawio
  template:
    metadata:
      labels:
        app: drawio
    spec:
      containers:
        - name: drawio
          image: yourdockerhubusername/drawio:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: drawio
spec:
  selector:
    app: drawio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
